{% set name = "fredapi" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9b3194fb60541991bd33f019c710d4a9580ecfb5e47efbf2d2571888a2aac02

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - pandas
    - python

test:
  imports:
    - fredapi

about:
  home: https://github.com/mortada/fredapi
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python API for Federal Reserve Economic Data (FRED) from St. Louis Fed

extra:
  recipe-maintainers:
    - tk3369
